### ISSUE TITLE
moose-examples/snippets/savemodel.py

### ISSUE THREAD

**Issue by malav4994** [BhallaLab/moose-examples#16]
loading model from genesis into moose, and converting it again to genesis one.

  File "savemodel.py", line 60, in <module>
    written = write('/model', 'testsave.g')
NameError: name 'write' is not defined

**Comment by hrani** [comment]
Do a git pull this was corrected about 4-5days before

**Comment by dilawar** [comment]
This is related to #12 which has been fixed. 

The function `moose.write` has been renamed to `moose.mooseWriteKkit` . Related to https://github.com/BhallaLab/moose-core/issues/156 .

**Comment by hrani** [comment]
This is nothing to do with SBML this was kkitWriter which was fixed  [6ebca](https://github.com/BhallaLab/moose-examples/blob/master/snippets/savemodel.py)

**Comment by malav4994** [comment]
Ok. got the modifications.
Still generating error.
This time, it can't load _moose from core.

Traceback (most recent call last):
  File "savemodel.py", line 54, in <module>
    import moose
  File "/home/mallo/moose/moose-core/python/moose/__init__.py", line 25, in <module>
    from .moose import *
  File "/home/mallo/moose/moose-core/python/moose/moose.py", line 17, in <module>
    from . import _moose
ImportError: cannot import name _moose

**Comment by malav4994** [comment]
clear...
