### ISSUE TITLE
Some files in neuroml are not running

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-examples#20]
@adityagilra 

Aditya,
These are not running, bcos of recent update in moose, in which if moose object exist and if we try to create same object (path) with different type/class, it complaints. "To get the existing object use `moose.element(obj)` instead"
 Earlier moose was silently assigning the old id to new variable which was wrong which is corrected.
E.g
pool =  moose.Pool('/model/Ca')
reac = moose.Reac('/model/Ca')
reac had moose id of pool which was wrong

1. [twoLIFxml_firing](https://github.com/BhallaLab/moose-examples/blob/master/neuroml/LIF/twoLIFxml_firing.py)

 postcomp = moose.Compartment(post_path)
  TypeError: cannot convert LIF to moose.Compartment. To get the existing object use `moose.element(obj)` instead

2. [Granule98.py](https://github.com/BhallaLab/moose-examples/blob/master/neuroml/GranuleCell/Granule98.py)
3. [Granule98_hsolve.py](https://github.com/BhallaLab/moose-examples/blob/master/neuroml/GranuleCell/Granule98_hsolve.py)
4. [allChannelsCell.py](https://github.com/BhallaLab/moose-examples/blob/master/neuroml/allChannelsCell/allChannelsCell.py)

somaIKCa = setupTable('somaIKCa',moose.HHChannel(soma_path+'/Gran_KCa_98'),'Gk')
TypeError: cannot convert HHChannel2D to moose.HHChannel. To get the existing object use `moose.element(obj)` instead

**Comment by dilawar** [comment]
Related to https://github.com/BhallaLab/moose-core/issues/186 

These script are fixed by https://github.com/BhallaLab/moose-core/issues/187
