### ISSUE TITLE
Running but not appropriately presented

### ISSUE THREAD

**Issue by malav4994** [BhallaLab/moose-examples#21]
Following files run properly without any issues, but do not provide any graphs or output text on terminal.

(I think as they are snippets, an user should get something to understand what just happened while execution of the files.)
- multiComptSigNeur.py
- Intfire.py

The following file runs properly, and generates graphs, too. It might be easier for a new user to understand if graphs would be labeled.
 - reacDiffSpinyNeuron.py

Following file runs properly and generates output properly. 
But in one of the comments it says the graph runs for 100 milliseceonds, while the command is moose.start(50), so am changing that data in comment.
- funcInputToPools : moose.start( 50.0 )

**Comment by dilawar** [comment]
If you are planning to fix them, take the ticket and reopen. None of the other developer seems interested in this ticket.
