### ISSUE TITLE
Animation in Documentation?

### ISSUE THREAD

**Issue by malav4994** [BhallaLab/moose-examples#22]
I was thinking of putting animation plots as videos in documentation. It is possible through the Sphinx.

If you permit it, I would like to have animation videos of following python files in snippets folder.
for time plots
 - loadMorphology.py              

For animation plot
- reacDiffBranchingNeuron.py  
- crossComptNeuroMesh.py 

Following is a like to the guide how it can be done using pylot.
https://jakevdp.github.io/blog/2012/08/18/matplotlib-animation-tutorial/

**Comment by dilawar** [comment]
Do you plan to use gif or some video format?

**Comment by malav4994** [comment]
nope, mp4

**Comment by dilawar** [comment]
We can host large video on documentation site with links. I don't think its a good idea to keep large video file in this repository.

**Comment by dilawar** [comment]
Closing it since there is no update on this issue. Reopen it if any progress is made on it or this idea has been abandoned.
