### ISSUE TITLE
some files while ploting gets seg fault

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-examples#23]
- [x] crossComptNeuroMesh.py , 
- [x] crossComptSimpleReac.py, 
- [x] crossComptSimpleReacGSSA.py, 
- [x] reacDiffConcGradient.py

These program which are in snippets folder, when run first time it runs fine, but multiple time run gives seg fault like (heisenbug )

**Comment by dilawar** [comment]
All these scripts are working fine with commit afbb5918d538
