### ISSUE TITLE
Rdesignuer/ex8.3_spine_vol_change.py getting runtime error

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-examples#75]
1. commit **17e1dd19046**  the file runs but result as show in the doc to the result what is displayed is slightly different

2.After git commit **c385807** the example stop working
 File "/home/harsha/MOOSE/delete-moose-core/python/rdesigneur/rdesigneur.py", line 1393, in _configureSolvers
    dmdsolve.buildNeuroMeshJunctions( smdsolve, pmdsolve )
RuntimeError: getFieldPropertyDestFinfo2::NotImplemented buildNeuroMeshJunctions for rttType Id,Id for oid /model[0]/chem[0]/dend[0]/dsolve[0]

3.After git commit **eafa8b2bfe0**
RuntimeError: getLookupValueFinfoItem::NotImplemented error

**Comment by upibhalla** [comment]
Checked in some fixes on zombie_gone branch. The buildNeuroMeshJunctions issue with PyBind is solved.

**Comment by hrani** [comment]
Yes Zombie_gone branch buildNeuroMeshJunction issue is gone but for the same file now we get segv upon debugging at Stoich::innerInstallReaction the segv fault.

**Comment by hrani** [comment]
In zombie _gone branch, seg fault is  around _configureSolver function in rdesigner when spineCompt.path is going to assign to stoich.reacSystemPath.

 if hasattr( self, 'spineCompt' ):
            ........
             smstoich.reacSystemPath = self.spineCompt.path + "/##"

I further debugged to see the reaction and its substrate, product and volume

for reaction

Name : CaM_bind_CaMKII

sub: [<Id: id=568 path=/model[0]/chem[0]/spine[0]/Ca_CaM class=Pool>] 9.243503319865049e-20
        [<Id: id=570 path=/model[0]/chem[0]/spine[0]/CaMKII class=Pool>] 9.243503319865049e-20

prd : [<Id: id=578 path=/model[0]/chem[0]/psd[0]/Ca_CaM_CaMKII class=Pool>] 1.188231417108964e-20

The product Ca_CaM_CaMKII is from different compartment

B. -------------------- porting moose-core for the same example --------------------
RuntimeError: getLookupValueFinfoItem::NotImplemented error 
rdeignuer.py @ def _buildAdaptor ()  

**elecComptList = moose.element( '/model/elec').spineIdsFromCompartmentIds[ mesh.elecComptList ]**

**Comment by hrani** [comment]
Fixed with latest moose-core git commit 33d1c249da9ba1e
